# special spring boot setting

---
spring:
  profiles:
    active: local
  main:
    # 關閉 spring boot logo
    banner-mode: 'off'
  mvc:
    view:
      # 使用 jsp 當 mvc 的 view 需宣告這二個，如果是用 thymeleaf 則有他的預設值
      prefix: /WEB-INF/jsp/
      suffix: .jsp


  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: none
  #   database: default
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        dialect: org.hibernate.dialect.MySQLDialect
##### default JPA setting , only for single Connection #####
#  datasource:
#    jdbc-url: jdbc:mysql://localhost:3306/books?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 1qaz2wsx
#    driver-class-name: com.mysql.cj.jdbc.Driver

books:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/book_store?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        ddl-auto: false
company:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/company?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        ddl-auto: false
#        format_sql: true
#        use_sql_comments: true
    # old mysql jdbc driver name was : com.mysql.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: trace


#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



#    jndi-name: java:comp/env/jdbc/books

#    books:
#      jndi-name: java:comp/env/jdbc/books
#    consumer:
#      jndi-name: java:comp/env/jdbc/consumer

my:
  mail:
    server: myoms.com.tw
    sender: mail@myoms.com.tw
    locale: zh-tw
your:
  date: 2010/01/01
  lists: 1,2,3,4,5

debug_mode: true

---
spring:
  profiles: local

proxy:
  domain: 'none'
  port: 0

server:
  port: 8080

---
spring:
  profiles: dev

proxy:
  domain: dev.proxy.com
  port: 3128

server:
  port: 8080


---
spring:
  profiles: stg

proxy:
  domain: stg.proxy.com
  port: 3128

server:
  port: 8080


---
spring:
  profiles: prod

proxy:
  domain: prod.proxy.com
  port: 3128

server:
  port: 8080
